site_name: اوکی‌آر

copyright: 'Copyright &copy; 2021 Mahdi Majidzadeh'

site_url: 'https://okr.mahdimajidzadeh.ir'
site_author: 'Mahdi Majidzadeh'

repo_name: 'okr'
repo_url: 'https://github.com/MahdiMajidzadeh/okr'

docs_dir: 'pages'
site_dir: 'docs'
lang: fa

theme:
  name: 'material'
  highlightjs: true
  # custom_dir: theme
  include_sidebar: false
  direction: 'rtl'
  language: 'fa'
  font: false

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta

extra_css: 
  - 'extra/style.css'  

extra:
  search:
    language: 'en, fa'

nav:
  - شروع: 'index.md'
  - پیش نیازها: 'requirement.md'