site_name: همه چیز درباره اوکی‌آر

copyright: 'Copyright &copy; 2021 Mahdi Majidzadeh'

site_url: 'https://okr.mahdimajidzadeh.ir'
site_author: 'Mahdi Majidzadeh'

repo_name: 'okr'
repo_url: 'https://github.com/MahdiMajidzadeh/okr'

theme:
  name: 'material'
  logo: extra/images/logo.png
  favicon: extra/images/fav.png
  palette:
    primary: teal
  highlightjs: true
  # custom_dir: theme
  include_sidebar: false
  direction: 'rtl'
  language: 'fa'
  font: false
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta

extra_css: 
  - 'extra/style.css'  

extra:
  search:
    language: 'en, fa'

nav:
  - دانشنامه:
    - تاریخچه: wiki/history.md
  - نمونه‌ها:
    - 'همه': 'example/index.md'
    - مارکتینگ: 'example/marketing.md'
  - منابع:
    - کتاب‌ها: 'sources/books.md'
  - شرکت‌ها:
    - همه: 'example/index.md'